spring.application.name=backend
spring.datasource.url=jdbc:mysql://mysql:3306/devops_db?createDatabaseIfNotExist=true
spring.datasource.username=devops
spring.datasource.password=devops123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
